"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['build/lib/Draft Analyzer.py']
DATA_FILES = [('Sounds',['Sounds/game_start.wav', 'Sounds/short_ringtone.wav']),
('Card Info',['Card Info/card_info.json']),
('Icons',['Icons/plat_icon.gif'])]
OPTIONS = {'argv_emulation': True,
 'iconfile': '/Users/linque/Sites/Draft-Analyzer/Icons/D-Icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
